package gdshader.modes;

import gdshader.types.*;

@:shaderType(spatial)
extern class Spatial {
	public function vertex(): Void;
	public function fragment(): Void;
	public function light(): Void;

	final CLIP_SPACE_FAR: Float;
	final E: Float;
	final EXPOSURE: Float;
	final IN_SHADOW_PASS: Bool;
	final OUTPUT_IS_SRGB: Bool;
	final PI: Float;
	final TAU: Float;
	final TIME: Float;
	@:allowedStages(vertex) final BONE_INDICES: UVec4;
	@:allowedStages(vertex) final BONE_WEIGHTS: Vec4;
	@:allowedStages(vertex) final CUSTOM0: Vec4;
	@:allowedStages(vertex) final CUSTOM1: Vec4;
	@:allowedStages(vertex) final CUSTOM2: Vec4;
	@:allowedStages(vertex) final CUSTOM3: Vec4;
	@:allowedStages(vertex) final INSTANCE_CUSTOM: Vec4;
	@:allowedStages(vertex) final INSTANCE_ID: Int;
	@:allowedStages(vertex) final MAIN_CAM_INV_VIEW_MATRIX: Mat4;
	@:allowedStages(vertex) final VERTEX_ID: Int;
	@:allowedStages(vertex) var MODELVIEW_MATRIX: Mat4;
	@:allowedStages(vertex) var MODELVIEW_NORMAL_MATRIX: Mat3;
	@:allowedStages(vertex) var POINT_SIZE: Float;
	@:allowedStages(vertex) var POSITION: Vec4;
	@:allowedStages(vertex) var Z_CLIP_SCALE: Float;
	@:allowedStages(fragment) final FRONT_FACING: Bool;
	@:allowedStages(fragment) final POINT_COORD: Vec2;
	@:allowedStages(fragment) var ALPHA_ANTIALIASING_EDGE: Float;
	@:allowedStages(fragment) var ALPHA_HASH_SCALE: Float;
	@:allowedStages(fragment) var ALPHA_SCISSOR_THRESHOLD: Float;
	@:allowedStages(fragment) var ALPHA_TEXTURE_COORDINATE: Vec2;
	@:allowedStages(fragment) var ANISOTROPY: Float;
	@:allowedStages(fragment) var ANISOTROPY_FLOW: Vec2;
	@:allowedStages(fragment) var AO: Float;
	@:allowedStages(fragment) var AO_LIGHT_AFFECT: Float;
	@:allowedStages(fragment) var BENT_NORMAL_MAP: Vec3;
	@:allowedStages(fragment) var CLEARCOAT: Float;
	@:allowedStages(fragment) var CLEARCOAT_ROUGHNESS: Float;
	@:allowedStages(fragment) var DEPTH: Float;
	@:allowedStages(fragment) var EMISSION: Vec3;
	@:allowedStages(fragment) var FOG: Vec4;
	@:allowedStages(fragment) var IRRADIANCE: Vec4;
	@:allowedStages(fragment) var LIGHT_VERTEX: Vec3;
	@:allowedStages(fragment) var NORMAL_MAP: Vec3;
	@:allowedStages(fragment) var NORMAL_MAP_DEPTH: Float;
	@:allowedStages(fragment) var PREMUL_ALPHA_FACTOR: Float;
	@:allowedStages(fragment) var RADIANCE: Vec4;
	@:allowedStages(fragment) var RIM: Float;
	@:allowedStages(fragment) var RIM_TINT: Float;
	@:allowedStages(fragment) var SPECULAR: Float;
	@:allowedStages(fragment) var SSS_STRENGTH: Float;
	@:allowedStages(fragment) var SSS_TRANSMITTANCE_BOOST: Float;
	@:allowedStages(fragment) var SSS_TRANSMITTANCE_COLOR: Vec4;
	@:allowedStages(fragment) var SSS_TRANSMITTANCE_DEPTH: Float;
	@:allowedStages(vertex, fragment) final CAMERA_DIRECTION_WORLD: Vec3;
	@:allowedStages(vertex, fragment) final CAMERA_POSITION_WORLD: Vec3;
	@:allowedStages(vertex, fragment) final CAMERA_VISIBLE_LAYERS: UInt;
	@:allowedStages(vertex, fragment) final EYE_OFFSET: Vec3;
	@:allowedStages(vertex, fragment) final MODEL_NORMAL_MATRIX: Mat3;
	@:allowedStages(vertex, fragment) final NODE_POSITION_VIEW: Vec3;
	@:allowedStages(vertex, fragment) final NODE_POSITION_WORLD: Vec3;
	@:allowedStages(vertex, fragment) final VIEW_INDEX: Int;
	@:allowedStages(vertex, fragment) final VIEW_MONO_LEFT: Int;
	@:allowedStages(vertex, fragment) final VIEW_RIGHT: Int;
	@:allowedStages(vertex, fragment) var BINORMAL: Vec3;
	@:allowedStages(vertex, fragment) var COLOR: Vec4;
	@:allowedStages(vertex, fragment) var TANGENT: Vec3;
	@:allowedStages(vertex, fragment) var VERTEX: Vec3;
	@:allowedStages(light) final ATTENUATION: Float;
	@:allowedStages(light) final LIGHT: Vec3;
	@:allowedStages(light) final LIGHT_COLOR: Vec3;
	@:allowedStages(light) final LIGHT_IS_DIRECTIONAL: Bool;
	@:allowedStages(light) final SPECULAR_AMOUNT: Float;
	@:allowedStages(light) var DIFFUSE_LIGHT: Vec3;
	@:allowedStages(light) var SPECULAR_LIGHT: Vec3;
	@:allowedStages(fragment, light) final FRAGCOORD: Vec4;
	@:allowedStages(fragment, light) final SCREEN_UV: Vec2;
	@:allowedStages(fragment, light) final VIEW: Vec3;
	@:allowedStages(fragment, light) var ALBEDO: Vec3;
	@:allowedStages(fragment, light) var ALPHA: Float;
	@:allowedStages(fragment, light) var BACKLIGHT: Vec3;
	@:allowedStages(fragment, light) var METALLIC: Float;
	@:allowedStages(vertex, fragment, light) final INV_PROJECTION_MATRIX: Mat4;
	@:allowedStages(vertex, fragment, light) final INV_VIEW_MATRIX: Mat4;
	@:allowedStages(vertex, fragment, light) final MODEL_MATRIX: Mat4;
	@:allowedStages(vertex, fragment, light) final VIEWPORT_SIZE: Vec2;
	@:allowedStages(vertex, fragment, light) final VIEW_MATRIX: Mat4;
	@:allowedStages(vertex, fragment, light) var NORMAL: Vec3;
	@:allowedStages(vertex, fragment, light) var PROJECTION_MATRIX: Mat4;
	@:allowedStages(vertex, fragment, light) var ROUGHNESS: Float;
	@:allowedStages(vertex, fragment, light) var UV2: Vec2;
	@:allowedStages(vertex, fragment, light) var UV: Vec2;
}
