package gdshader;

import gdshader.types.*;

overload extern function bvec2(bool: Bool): BVec2;
overload extern function bvec2(x: Bool, y: Bool): BVec2;
overload extern function bvec2(bvec2: BVec2): BVec2;
overload extern function bvec2(ivec2: IVec2): BVec2;
overload extern function bvec2(uvec2: UVec2): BVec2;
overload extern function bvec2(vec2: Vec2): BVec2;
overload extern function bvec3(bool: Bool): BVec3;
overload extern function bvec3(x: Bool, y: Bool, z: Bool): BVec3;
overload extern function bvec3(bvec2: BVec2, bool: Bool): BVec3;
overload extern function bvec3(bool: Bool, bvec2: BVec2): BVec3;
overload extern function bvec3(bvec3: BVec3): BVec3;
overload extern function bvec3(ivec3: IVec3): BVec3;
overload extern function bvec3(uvec3: UVec3): BVec3;
overload extern function bvec3(vec3: Vec3): BVec3;
overload extern function bvec4(bool: Bool): BVec4;
overload extern function bvec4(x: Bool, y: Bool, z: Bool, w: Bool): BVec4;
overload extern function bvec4(bool1: Bool, bvec2: BVec2, bool2: Bool): BVec4;
overload extern function bvec4(bvec2: BVec2, bool1: Bool, bool2: Bool): BVec4;
overload extern function bvec4(bool1: Bool, bool2: Bool, bvec2: BVec2): BVec4;
overload extern function bvec4(bool: Bool, bvec3: BVec3): BVec4;
overload extern function bvec4(bvec3: BVec3, bool: Bool): BVec4;
overload extern function bvec4(x: BVec2, y: BVec2): BVec4;
overload extern function bvec4(bvec4: BVec4): BVec4;
overload extern function bvec4(ivec4: IVec4): BVec4;
overload extern function bvec4(uvec4: UVec4): BVec4;
overload extern function bvec4(vec4: Vec4): BVec4;
overload extern function vec2(float: Float): Vec2;
overload extern function vec2(x: Float, y: Float): Vec2;
overload extern function vec2(bvec2: BVec2): Vec2;
overload extern function vec2(ivec2: IVec2): Vec2;
overload extern function vec2(uvec2: UVec2): Vec2;
overload extern function vec2(vec2: Vec2): Vec2;
overload extern function vec3(float: Float): Vec3;
overload extern function vec3(x: Float, y: Float, z: Float): Vec3;
overload extern function vec3(vec2: Vec2, float: Float): Vec3;
overload extern function vec3(float: Float, vec2: Vec2): Vec3;
overload extern function vec3(bvec3: BVec3): Vec3;
overload extern function vec3(ivec3: IVec3): Vec3;
overload extern function vec3(uvec3: UVec3): Vec3;
overload extern function vec3(vec3: Vec3): Vec3;
overload extern function vec4(float: Float): Vec4;
overload extern function vec4(x: Float, y: Float, z: Float, w: Float): Vec4;
overload extern function vec4(float1: Float, vec2: Vec2, float2: Float): Vec4;
overload extern function vec4(vec2: Vec2, float1: Float, float2: Float): Vec4;
overload extern function vec4(float1: Float, float2: Float, vec2: Vec2): Vec4;
overload extern function vec4(float: Float, vec3: Vec3): Vec4;
overload extern function vec4(vec3: Vec3, float: Float): Vec4;
overload extern function vec4(x: Vec2, y: Vec2): Vec4;
overload extern function vec4(bvec4: BVec4): Vec4;
overload extern function vec4(ivec4: IVec4): Vec4;
overload extern function vec4(uvec4: UVec4): Vec4;
overload extern function vec4(vec4: Vec4): Vec4;
overload extern function ivec2(int: Int): IVec2;
overload extern function ivec2(x: Int, y: Int): IVec2;
overload extern function ivec2(bvec2: BVec2): IVec2;
overload extern function ivec2(ivec2: IVec2): IVec2;
overload extern function ivec2(uvec2: UVec2): IVec2;
overload extern function ivec2(vec2: Vec2): IVec2;
overload extern function ivec3(int: Int): IVec3;
overload extern function ivec3(x: Int, y: Int, z: Int): IVec3;
overload extern function ivec3(ivec2: IVec2, int: Int): IVec3;
overload extern function ivec3(int: Int, ivec2: IVec2): IVec3;
overload extern function ivec3(bvec3: BVec3): IVec3;
overload extern function ivec3(ivec3: IVec3): IVec3;
overload extern function ivec3(uvec3: UVec3): IVec3;
overload extern function ivec3(vec3: Vec3): IVec3;
overload extern function ivec4(int: Int): IVec4;
overload extern function ivec4(x: Int, y: Int, z: Int, w: Int): IVec4;
overload extern function ivec4(int1: Int, ivec2: IVec2, int2: Int): IVec4;
overload extern function ivec4(ivec2: IVec2, int1: Int, int2: Int): IVec4;
overload extern function ivec4(int1: Int, int2: Int, ivec2: IVec2): IVec4;
overload extern function ivec4(int: Int, ivec3: IVec3): IVec4;
overload extern function ivec4(ivec3: IVec3, int: Int): IVec4;
overload extern function ivec4(x: IVec2, y: IVec2): IVec4;
overload extern function ivec4(bvec4: BVec4): IVec4;
overload extern function ivec4(ivec4: IVec4): IVec4;
overload extern function ivec4(uvec4: UVec4): IVec4;
overload extern function ivec4(vec4: Vec4): IVec4;
overload extern function uvec2(uint: UInt): UVec2;
overload extern function uvec2(x: UInt, y: UInt): UVec2;
overload extern function uvec2(bvec2: BVec2): UVec2;
overload extern function uvec2(ivec2: IVec2): UVec2;
overload extern function uvec2(uvec2: UVec2): UVec2;
overload extern function uvec2(vec2: Vec2): UVec2;
overload extern function uvec3(uint: UInt): UVec3;
overload extern function uvec3(x: UInt, y: UInt, z: UInt): UVec3;
overload extern function uvec3(uvec2: UVec2, uint: UInt): UVec3;
overload extern function uvec3(uint: UInt, uvec2: UVec2): UVec3;
overload extern function uvec3(bvec3: BVec3): UVec3;
overload extern function uvec3(ivec3: IVec3): UVec3;
overload extern function uvec3(uvec3: UVec3): UVec3;
overload extern function uvec3(vec3: Vec3): UVec3;
overload extern function uvec4(uint: UInt): UVec4;
overload extern function uvec4(x: UInt, y: UInt, z: UInt, w: UInt): UVec4;
overload extern function uvec4(uint1: UInt, uvec2: UVec2, uint2: UInt): UVec4;
overload extern function uvec4(uvec2: UVec2, uint1: UInt, uint2: UInt): UVec4;
overload extern function uvec4(uint1: UInt, uint2: UInt, uvec2: UVec2): UVec4;
overload extern function uvec4(uint: UInt, uvec3: UVec3): UVec4;
overload extern function uvec4(uvec3: UVec3, uint: UInt): UVec4;
overload extern function uvec4(x: UVec2, y: UVec2): UVec4;
overload extern function uvec4(bvec4: BVec4): UVec4;
overload extern function uvec4(ivec4: IVec4): UVec4;
overload extern function uvec4(uvec4: UVec4): UVec4;
overload extern function uvec4(vec4: Vec4): UVec4;
overload extern function mat2(x: Vec2, y: Vec2): Mat2;
overload extern function mat2(float: Float): Mat2;
overload extern function mat2(mat3: Mat3): Mat2;
overload extern function mat2(mat4: Mat4): Mat2;
overload extern function mat3(x: Vec3, y: Vec3, z: Vec3): Mat3;
overload extern function mat3(float: Float): Mat3;
overload extern function mat3(mat2: Mat2): Mat3;
overload extern function mat3(mat4: Mat4): Mat3;
overload extern function mat4(x: Vec4, y: Vec4, z: Vec4, w: Vec4): Mat4;
overload extern function mat4(float: Float): Mat4;
overload extern function mat4(mat2: Mat2): Mat4;
overload extern function mat4(mat3: Mat3): Mat4;
overload extern function int(bool: Bool): Int;
overload extern function int(int: Int): Int;
overload extern function int(uint: UInt): Int;
overload extern function int(float: Float): Int;
overload extern function float(bool: Bool): Float;
overload extern function float(int: Int): Float;
overload extern function float(uint: UInt): Float;
overload extern function float(float: Float): Float;
overload extern function uint(bool: Bool): UInt;
overload extern function uint(int: Int): UInt;
overload extern function uint(uint: UInt): UInt;
overload extern function uint(float: Float): UInt;
overload extern function bool(bool: Bool): Bool;
overload extern function bool(int: Int): Bool;
overload extern function bool(uint: UInt): Bool;
overload extern function bool(float: Float): Bool;
