package gdshader;

import gdshader.types.*;

overload extern function radians(degrees: Float): Float;
overload extern function radians(degrees: Vec2): Vec2;
overload extern function radians(degrees: Vec3): Vec3;
overload extern function radians(degrees: Vec4): Vec4;
overload extern function degrees(radians: Float): Float;
overload extern function degrees(radians: Vec2): Vec2;
overload extern function degrees(radians: Vec3): Vec3;
overload extern function degrees(radians: Vec4): Vec4;
overload extern function sin(angle: Float): Float;
overload extern function sin(angle: Vec2): Vec2;
overload extern function sin(angle: Vec3): Vec3;
overload extern function sin(angle: Vec4): Vec4;
overload extern function cos(angle: Float): Float;
overload extern function cos(angle: Vec2): Vec2;
overload extern function cos(angle: Vec3): Vec3;
overload extern function cos(angle: Vec4): Vec4;
overload extern function tan(angle: Float): Float;
overload extern function tan(angle: Vec2): Vec2;
overload extern function tan(angle: Vec3): Vec3;
overload extern function tan(angle: Vec4): Vec4;
overload extern function asin(x: Float): Float;
overload extern function asin(x: Vec2): Vec2;
overload extern function asin(x: Vec3): Vec3;
overload extern function asin(x: Vec4): Vec4;
overload extern function acos(x: Float): Float;
overload extern function acos(x: Vec2): Vec2;
overload extern function acos(x: Vec3): Vec3;
overload extern function acos(x: Vec4): Vec4;
overload extern function atan(y_over_x: Float): Float;
overload extern function atan(y_over_x: Vec2): Vec2;
overload extern function atan(y_over_x: Vec3): Vec3;
overload extern function atan(y_over_x: Vec4): Vec4;
overload extern function atan(y: Float, x: Float): Float;
overload extern function atan(y: Vec2, x: Vec2): Vec2;
overload extern function atan(y: Vec3, x: Vec3): Vec3;
overload extern function atan(y: Vec4, x: Vec4): Vec4;
overload extern function sinh(x: Float): Float;
overload extern function sinh(x: Vec2): Vec2;
overload extern function sinh(x: Vec3): Vec3;
overload extern function sinh(x: Vec4): Vec4;
overload extern function cosh(x: Float): Float;
overload extern function cosh(x: Vec2): Vec2;
overload extern function cosh(x: Vec3): Vec3;
overload extern function cosh(x: Vec4): Vec4;
overload extern function tanh(x: Float): Float;
overload extern function tanh(x: Vec2): Vec2;
overload extern function tanh(x: Vec3): Vec3;
overload extern function tanh(x: Vec4): Vec4;
overload extern function asinh(x: Float): Float;
overload extern function asinh(x: Vec2): Vec2;
overload extern function asinh(x: Vec3): Vec3;
overload extern function asinh(x: Vec4): Vec4;
overload extern function acosh(x: Float): Float;
overload extern function acosh(x: Vec2): Vec2;
overload extern function acosh(x: Vec3): Vec3;
overload extern function acosh(x: Vec4): Vec4;
overload extern function atanh(x: Float): Float;
overload extern function atanh(x: Vec2): Vec2;
overload extern function atanh(x: Vec3): Vec3;
overload extern function atanh(x: Vec4): Vec4;
overload extern function pow(x: Float, y: Float): Float;
overload extern function pow(x: Vec2, y: Vec2): Vec2;
overload extern function pow(x: Vec3, y: Vec3): Vec3;
overload extern function pow(x: Vec4, y: Vec4): Vec4;
overload extern function exp(x: Float): Float;
overload extern function exp(x: Vec2): Vec2;
overload extern function exp(x: Vec3): Vec3;
overload extern function exp(x: Vec4): Vec4;
overload extern function log(x: Float): Float;
overload extern function log(x: Vec2): Vec2;
overload extern function log(x: Vec3): Vec3;
overload extern function log(x: Vec4): Vec4;
overload extern function exp2(x: Float): Float;
overload extern function exp2(x: Vec2): Vec2;
overload extern function exp2(x: Vec3): Vec3;
overload extern function exp2(x: Vec4): Vec4;
overload extern function log2(x: Float): Float;
overload extern function log2(x: Vec2): Vec2;
overload extern function log2(x: Vec3): Vec3;
overload extern function log2(x: Vec4): Vec4;
overload extern function sqrt(x: Float): Float;
overload extern function sqrt(x: Vec2): Vec2;
overload extern function sqrt(x: Vec3): Vec3;
overload extern function sqrt(x: Vec4): Vec4;
overload extern function inversesqrt(x: Float): Float;
overload extern function inversesqrt(x: Vec2): Vec2;
overload extern function inversesqrt(x: Vec3): Vec3;
overload extern function inversesqrt(x: Vec4): Vec4;
overload extern function abs(x: Float): Float;
overload extern function abs(x: Vec2): Vec2;
overload extern function abs(x: Vec3): Vec3;
overload extern function abs(x: Vec4): Vec4;
overload extern function abs(x: Int): Int;
overload extern function abs(x: IVec2): IVec2;
overload extern function abs(x: IVec3): IVec3;
overload extern function abs(x: IVec4): IVec4;
overload extern function sign(x: Float): Float;
overload extern function sign(x: Vec2): Vec2;
overload extern function sign(x: Vec3): Vec3;
overload extern function sign(x: Vec4): Vec4;
overload extern function sign(x: Int): Int;
overload extern function sign(x: IVec2): IVec2;
overload extern function sign(x: IVec3): IVec3;
overload extern function sign(x: IVec4): IVec4;
overload extern function floor(x: Float): Float;
overload extern function floor(x: Vec2): Vec2;
overload extern function floor(x: Vec3): Vec3;
overload extern function floor(x: Vec4): Vec4;
overload extern function trunc(x: Float): Float;
overload extern function trunc(x: Vec2): Vec2;
overload extern function trunc(x: Vec3): Vec3;
overload extern function trunc(x: Vec4): Vec4;
overload extern function round(x: Float): Float;
overload extern function round(x: Vec2): Vec2;
overload extern function round(x: Vec3): Vec3;
overload extern function round(x: Vec4): Vec4;
overload extern function roundEven(x: Float): Float;
overload extern function roundEven(x: Vec2): Vec2;
overload extern function roundEven(x: Vec3): Vec3;
overload extern function roundEven(x: Vec4): Vec4;
overload extern function ceil(x: Float): Float;
overload extern function ceil(x: Vec2): Vec2;
overload extern function ceil(x: Vec3): Vec3;
overload extern function ceil(x: Vec4): Vec4;
overload extern function fract(x: Float): Float;
overload extern function fract(x: Vec2): Vec2;
overload extern function fract(x: Vec3): Vec3;
overload extern function fract(x: Vec4): Vec4;
overload extern function mod(x: Float, y: Float): Float;
overload extern function mod(x: Vec2, y: Vec2): Vec2;
overload extern function mod(x: Vec2, y: Float): Vec2;
overload extern function mod(x: Vec3, y: Vec3): Vec3;
overload extern function mod(x: Vec3, y: Float): Vec3;
overload extern function mod(x: Vec4, y: Vec4): Vec4;
overload extern function mod(x: Vec4, y: Float): Vec4;
overload extern function modf(x: Float, i: Float): Float;
overload extern function modf(x: Vec2, i: Vec2): Vec2;
overload extern function modf(x: Vec3, i: Vec3): Vec3;
overload extern function modf(x: Vec4, i: Vec4): Vec4;
overload extern function min(a: Float, b: Float): Float;
overload extern function min(a: Vec2, b: Vec2): Vec2;
overload extern function min(a: Vec2, b: Float): Vec2;
overload extern function min(a: Vec3, b: Vec3): Vec3;
overload extern function min(a: Vec3, b: Float): Vec3;
overload extern function min(a: Vec4, b: Vec4): Vec4;
overload extern function min(a: Vec4, b: Float): Vec4;
overload extern function min(a: Int, b: Int): Int;
overload extern function min(a: IVec2, b: IVec2): IVec2;
overload extern function min(a: IVec2, b: Int): IVec2;
overload extern function min(a: IVec3, b: IVec3): IVec3;
overload extern function min(a: IVec3, b: Int): IVec3;
overload extern function min(a: IVec4, b: IVec4): IVec4;
overload extern function min(a: IVec4, b: Int): IVec4;
overload extern function min(a: UInt, b: UInt): UInt;
overload extern function min(a: UVec2, b: UVec2): UVec2;
overload extern function min(a: UVec2, b: UInt): UVec2;
overload extern function min(a: UVec3, b: UVec3): UVec3;
overload extern function min(a: UVec3, b: UInt): UVec3;
overload extern function min(a: UVec4, b: UVec4): UVec4;
overload extern function min(a: UVec4, b: UInt): UVec4;
overload extern function max(a: Float, b: Float): Float;
overload extern function max(a: Vec2, b: Vec2): Vec2;
overload extern function max(a: Vec2, b: Float): Vec2;
overload extern function max(a: Vec3, b: Vec3): Vec3;
overload extern function max(a: Vec3, b: Float): Vec3;
overload extern function max(a: Vec4, b: Vec4): Vec4;
overload extern function max(a: Vec4, b: Float): Vec4;
overload extern function max(a: Int, b: Int): Int;
overload extern function max(a: IVec2, b: IVec2): IVec2;
overload extern function max(a: IVec2, b: Int): IVec2;
overload extern function max(a: IVec3, b: IVec3): IVec3;
overload extern function max(a: IVec3, b: Int): IVec3;
overload extern function max(a: IVec4, b: IVec4): IVec4;
overload extern function max(a: IVec4, b: Int): IVec4;
overload extern function max(a: UInt, b: UInt): UInt;
overload extern function max(a: UVec2, b: UVec2): UVec2;
overload extern function max(a: UVec2, b: UInt): UVec2;
overload extern function max(a: UVec3, b: UVec3): UVec3;
overload extern function max(a: UVec3, b: UInt): UVec3;
overload extern function max(a: UVec4, b: UVec4): UVec4;
overload extern function max(a: UVec4, b: UInt): UVec4;
overload extern function clamp(x: Float, minVal: Float, maxVal: Float): Float;
overload extern function clamp(x: Vec2, minVal: Vec2, maxVal: Vec2): Vec2;
overload extern function clamp(x: Vec3, minVal: Vec3, maxVal: Vec3): Vec3;
overload extern function clamp(x: Vec4, minVal: Vec4, maxVal: Vec4): Vec4;
overload extern function clamp(x: Vec2, minVal: Float, maxVal: Float): Vec2;
overload extern function clamp(x: Vec3, minVal: Float, maxVal: Float): Vec3;
overload extern function clamp(x: Vec4, minVal: Float, maxVal: Float): Vec4;
overload extern function clamp(x: Int, minVal: Int, maxVal: Int): Int;
overload extern function clamp(x: IVec2, minVal: IVec2, maxVal: IVec2): IVec2;
overload extern function clamp(x: IVec3, minVal: IVec3, maxVal: IVec3): IVec3;
overload extern function clamp(x: IVec4, minVal: IVec4, maxVal: IVec4): IVec4;
overload extern function clamp(x: IVec2, minVal: Int, maxVal: Int): IVec2;
overload extern function clamp(x: IVec3, minVal: Int, maxVal: Int): IVec3;
overload extern function clamp(x: IVec4, minVal: Int, maxVal: Int): IVec4;
overload extern function clamp(x: UInt, minVal: UInt, maxVal: UInt): UInt;
overload extern function clamp(x: UVec2, minVal: UVec2, maxVal: UVec2): UVec2;
overload extern function clamp(x: UVec3, minVal: UVec3, maxVal: UVec3): UVec3;
overload extern function clamp(x: UVec4, minVal: UVec4, maxVal: UVec4): UVec4;
overload extern function clamp(x: UVec2, minVal: UInt, maxVal: UInt): UVec2;
overload extern function clamp(x: UVec3, minVal: UInt, maxVal: UInt): UVec3;
overload extern function clamp(x: UVec4, minVal: UInt, maxVal: UInt): UVec4;
overload extern function mix(a: Float, b: Float, value: Float): Float;
overload extern function mix(a: Vec2, b: Vec2, value: Float): Vec2;
overload extern function mix(a: Vec2, b: Vec2, value: BVec2): Vec2;
overload extern function mix(a: Vec2, b: Vec2, value: Vec2): Vec2;
overload extern function mix(a: Vec3, b: Vec3, value: Float): Vec3;
overload extern function mix(a: Vec3, b: Vec3, value: BVec3): Vec3;
overload extern function mix(a: Vec3, b: Vec3, value: Vec3): Vec3;
overload extern function mix(a: Vec4, b: Vec4, value: Float): Vec4;
overload extern function mix(a: Vec4, b: Vec4, value: BVec4): Vec4;
overload extern function mix(a: Vec4, b: Vec4, value: Vec4): Vec4;
overload extern function step(edge: Float, x: Float): Float;
overload extern function step(edge: Vec2, x: Vec2): Vec2;
overload extern function step(edge: Vec3, x: Vec3): Vec3;
overload extern function step(edge: Vec4, x: Vec4): Vec4;
overload extern function step(edge: Float, x: Vec2): Vec2;
overload extern function step(edge: Float, x: Vec3): Vec3;
overload extern function step(edge: Float, x: Vec4): Vec4;
overload extern function smoothstep(edge0: Float, edge1: Float, value: Float): Float;
overload extern function smoothstep(edge0: Vec2, edge1: Vec2, value: Vec2): Vec2;
overload extern function smoothstep(edge0: Vec3, edge1: Vec3, value: Vec3): Vec3;
overload extern function smoothstep(edge0: Vec4, edge1: Vec4, value: Vec4): Vec4;
overload extern function smoothstep(edge0: Float, edge1: Float, value: Vec2): Vec2;
overload extern function smoothstep(edge0: Float, edge1: Float, value: Vec3): Vec3;
overload extern function smoothstep(edge0: Float, edge1: Float, value: Vec4): Vec4;
overload extern function isnan(x: Float): Bool;
overload extern function isnan(x: Vec2): BVec2;
overload extern function isnan(x: Vec3): BVec3;
overload extern function isnan(x: Vec4): BVec4;
overload extern function isinf(x: Float): Bool;
overload extern function isinf(x: Vec2): BVec2;
overload extern function isinf(x: Vec3): BVec3;
overload extern function isinf(x: Vec4): BVec4;
overload extern function floatBitsToInt(x: Float): Int;
overload extern function floatBitsToInt(x: Vec2): IVec2;
overload extern function floatBitsToInt(x: Vec3): IVec3;
overload extern function floatBitsToInt(x: Vec4): IVec4;
overload extern function floatBitsToUint(x: Float): UInt;
overload extern function floatBitsToUint(x: Vec2): UVec2;
overload extern function floatBitsToUint(x: Vec3): UVec3;
overload extern function floatBitsToUint(x: Vec4): UVec4;
overload extern function intBitsToFloat(x: Int): Float;
overload extern function intBitsToFloat(x: IVec2): Vec2;
overload extern function intBitsToFloat(x: IVec3): Vec3;
overload extern function intBitsToFloat(x: IVec4): Vec4;
overload extern function uintBitsToFloat(x: UInt): Float;
overload extern function uintBitsToFloat(x: UVec2): Vec2;
overload extern function uintBitsToFloat(x: UVec3): Vec3;
overload extern function uintBitsToFloat(x: UVec4): Vec4;
overload extern function length(x: Float): Float;
overload extern function length(x: Vec2): Float;
overload extern function length(x: Vec3): Float;
overload extern function length(x: Vec4): Float;
overload extern function length(): Int;
overload extern function distance(a: Float, b: Float): Float;
overload extern function distance(a: Vec2, b: Vec2): Float;
overload extern function distance(a: Vec3, b: Vec3): Float;
overload extern function distance(a: Vec4, b: Vec4): Float;
overload extern function dot(a: Float, b: Float): Float;
overload extern function dot(a: Vec2, b: Vec2): Float;
overload extern function dot(a: Vec3, b: Vec3): Float;
overload extern function dot(a: Vec4, b: Vec4): Float;
extern function cross(a: Vec3, b: Vec3): Vec3;
overload extern function normalize(v: Float): Float;
overload extern function normalize(v: Vec2): Vec2;
overload extern function normalize(v: Vec3): Vec3;
overload extern function normalize(v: Vec4): Vec4;
overload extern function reflect(I: Vec2, N: Vec2): Vec2;
overload extern function reflect(I: Vec3, N: Vec3): Vec3;
overload extern function reflect(I: Vec4, N: Vec4): Vec4;
overload extern function refract(I: Vec2, N: Vec2, eta: Float): Vec2;
overload extern function refract(I: Vec3, N: Vec3, eta: Float): Vec3;
overload extern function refract(I: Vec4, N: Vec4, eta: Float): Vec4;
overload extern function faceforward(N: Vec2, I: Vec2, Nref: Vec2): Vec2;
overload extern function faceforward(N: Vec3, I: Vec3, Nref: Vec3): Vec3;
overload extern function faceforward(N: Vec4, I: Vec4, Nref: Vec4): Vec4;
overload extern function matrixCompMult(a: Mat2, b: Mat2): Mat2;
overload extern function matrixCompMult(a: Mat3, b: Mat3): Mat3;
overload extern function matrixCompMult(a: Mat4, b: Mat4): Mat4;
overload extern function outerProduct(c: Vec2, r: Vec2): Mat2;
overload extern function outerProduct(c: Vec3, r: Vec3): Mat3;
overload extern function outerProduct(c: Vec4, r: Vec4): Mat4;
overload extern function transpose(m: Mat2): Mat2;
overload extern function transpose(m: Mat3): Mat3;
overload extern function transpose(m: Mat4): Mat4;
overload extern function determinant(m: Mat2): Float;
overload extern function determinant(m: Mat3): Float;
overload extern function determinant(m: Mat4): Float;
overload extern function inverse(m: Mat2): Mat2;
overload extern function inverse(m: Mat3): Mat3;
overload extern function inverse(m: Mat4): Mat4;
overload extern function lessThan(a: Vec2, b: Vec2): BVec2;
overload extern function lessThan(a: Vec3, b: Vec3): BVec3;
overload extern function lessThan(a: Vec4, b: Vec4): BVec4;
overload extern function lessThan(a: IVec2, b: IVec2): BVec2;
overload extern function lessThan(a: IVec3, b: IVec3): BVec3;
overload extern function lessThan(a: IVec4, b: IVec4): BVec4;
overload extern function lessThan(a: UVec3, b: UVec3): BVec3;
overload extern function lessThan(a: UVec4, b: UVec4): BVec4;
overload extern function lessThan(a: UVec2, b: UVec2): BVec2;
overload extern function greaterThan(a: Vec2, b: Vec2): BVec2;
overload extern function greaterThan(a: Vec3, b: Vec3): BVec3;
overload extern function greaterThan(a: Vec4, b: Vec4): BVec4;
overload extern function greaterThan(a: IVec2, b: IVec2): BVec2;
overload extern function greaterThan(a: IVec3, b: IVec3): BVec3;
overload extern function greaterThan(a: IVec4, b: IVec4): BVec4;
overload extern function greaterThan(a: UVec2, b: UVec2): BVec2;
overload extern function greaterThan(a: UVec3, b: UVec3): BVec3;
overload extern function greaterThan(a: UVec4, b: UVec4): BVec4;
overload extern function lessThanEqual(a: Vec2, b: Vec2): BVec2;
overload extern function lessThanEqual(a: Vec3, b: Vec3): BVec3;
overload extern function lessThanEqual(a: Vec4, b: Vec4): BVec4;
overload extern function lessThanEqual(a: IVec2, b: IVec2): BVec2;
overload extern function lessThanEqual(a: IVec3, b: IVec3): BVec3;
overload extern function lessThanEqual(a: IVec4, b: IVec4): BVec4;
overload extern function lessThanEqual(a: UVec2, b: UVec2): BVec2;
overload extern function lessThanEqual(a: UVec3, b: UVec3): BVec3;
overload extern function lessThanEqual(a: UVec4, b: UVec4): BVec4;
overload extern function greaterThanEqual(a: Vec2, b: Vec2): BVec2;
overload extern function greaterThanEqual(a: Vec3, b: Vec3): BVec3;
overload extern function greaterThanEqual(a: Vec4, b: Vec4): BVec4;
overload extern function greaterThanEqual(a: IVec2, b: IVec2): BVec2;
overload extern function greaterThanEqual(a: IVec3, b: IVec3): BVec3;
overload extern function greaterThanEqual(a: IVec4, b: IVec4): BVec4;
overload extern function greaterThanEqual(a: UVec2, b: UVec2): BVec2;
overload extern function greaterThanEqual(a: UVec3, b: UVec3): BVec3;
overload extern function greaterThanEqual(a: UVec4, b: UVec4): BVec4;
overload extern function equal(a: Vec2, b: Vec2): BVec2;
overload extern function equal(a: Vec3, b: Vec3): BVec3;
overload extern function equal(a: Vec4, b: Vec4): BVec4;
overload extern function equal(a: IVec2, b: IVec2): BVec2;
overload extern function equal(a: IVec3, b: IVec3): BVec3;
overload extern function equal(a: IVec4, b: IVec4): BVec4;
overload extern function equal(a: UVec2, b: UVec2): BVec2;
overload extern function equal(a: UVec3, b: UVec3): BVec3;
overload extern function equal(a: UVec4, b: UVec4): BVec4;
overload extern function equal(a: BVec2, b: BVec2): BVec2;
overload extern function equal(a: BVec3, b: BVec3): BVec3;
overload extern function equal(a: BVec4, b: BVec4): BVec4;
overload extern function notEqual(a: Vec2, b: Vec2): BVec2;
overload extern function notEqual(a: Vec3, b: Vec3): BVec3;
overload extern function notEqual(a: Vec4, b: Vec4): BVec4;
overload extern function notEqual(a: IVec2, b: IVec2): BVec2;
overload extern function notEqual(a: IVec3, b: IVec3): BVec3;
overload extern function notEqual(a: IVec4, b: IVec4): BVec4;
overload extern function notEqual(a: UVec2, b: UVec2): BVec2;
overload extern function notEqual(a: UVec3, b: UVec3): BVec3;
overload extern function notEqual(a: UVec4, b: UVec4): BVec4;
overload extern function notEqual(a: BVec2, b: BVec2): BVec2;
overload extern function notEqual(a: BVec3, b: BVec3): BVec3;
overload extern function notEqual(a: BVec4, b: BVec4): BVec4;
overload extern function any(x: BVec2): Bool;
overload extern function any(x: BVec3): Bool;
overload extern function any(x: BVec4): Bool;
overload extern function all(x: BVec2): Bool;
overload extern function all(x: BVec3): Bool;
overload extern function all(x: BVec4): Bool;
overload extern function not(x: BVec2): BVec2;
overload extern function not(x: BVec3): BVec3;
overload extern function not(x: BVec4): BVec4;
overload extern function textureSize(sampler: Sampler2D, lod: Int): IVec2;
overload extern function textureSize(sampler: ISampler2D, lod: Int): IVec2;
overload extern function textureSize(sampler: USampler2D, lod: Int): IVec2;
overload extern function textureSize(sampler: Sampler2DArray, lod: Int): IVec3;
overload extern function textureSize(sampler: ISampler2DArray, lod: Int): IVec3;
overload extern function textureSize(sampler: USampler2DArray, lod: Int): IVec3;
overload extern function textureSize(sampler: Sampler3D, lod: Int): IVec3;
overload extern function textureSize(sampler: ISampler3D, lod: Int): IVec3;
overload extern function textureSize(sampler: USampler3D, lod: Int): IVec3;
overload extern function textureSize(sampler: SamplerCube, lod: Int): IVec2;
overload extern function textureSize(sampler: SamplerCubeArray, lod: Int): IVec2;
overload extern function texture(sampler: Sampler2D, coords: Vec2): Vec4;
overload extern function texture(sampler: Sampler2D, coords: Vec2, bias: Float): Vec4;
overload extern function texture(sampler: USampler2D, coords: Vec2): UVec4;
overload extern function texture(sampler: USampler2D, coords: Vec2, bias: Float): UVec4;
overload extern function texture(sampler: ISampler2D, coords: Vec2): IVec4;
overload extern function texture(sampler: ISampler2D, coords: Vec2, bias: Float): IVec4;
overload extern function texture(sampler: Sampler2DArray, coords: Vec3): Vec4;
overload extern function texture(sampler: Sampler2DArray, coords: Vec3, bias: Float): Vec4;
overload extern function texture(sampler: USampler2DArray, coords: Vec3): UVec4;
overload extern function texture(sampler: USampler2DArray, coords: Vec3, bias: Float): UVec4;
overload extern function texture(sampler: ISampler2DArray, coords: Vec3): IVec4;
overload extern function texture(sampler: ISampler2DArray, coords: Vec3, bias: Float): IVec4;
overload extern function texture(sampler: Sampler3D, coords: Vec3): Vec4;
overload extern function texture(sampler: Sampler3D, coords: Vec3, bias: Float): Vec4;
overload extern function texture(sampler: USampler3D, coords: Vec3): UVec4;
overload extern function texture(sampler: USampler3D, coords: Vec3, bias: Float): UVec4;
overload extern function texture(sampler: ISampler3D, coords: Vec3): IVec4;
overload extern function texture(sampler: ISampler3D, coords: Vec3, bias: Float): IVec4;
overload extern function texture(sampler: SamplerCube, coords: Vec3): Vec4;
overload extern function texture(sampler: SamplerCube, coords: Vec3, bias: Float): Vec4;
overload extern function texture(sampler: SamplerCubeArray, coords: Vec4): Vec4;
overload extern function texture(sampler: SamplerCubeArray, coords: Vec4, bias: Float): Vec4;
overload extern function texture(sampler: SamplerExternalOES, coords: Vec2): Vec4;
overload extern function texture(sampler: SamplerExternalOES, coords: Vec2, bias: Float): Vec4;
overload extern function textureProj(sampler: Sampler2D, coords: Vec3): Vec4;
overload extern function textureProj(sampler: Sampler2D, coords: Vec4): Vec4;
overload extern function textureProj(sampler: Sampler2D, coords: Vec3, bias: Float): Vec4;
overload extern function textureProj(sampler: Sampler2D, coords: Vec4, bias: Float): Vec4;
overload extern function textureProj(sampler: ISampler2D, coords: Vec3): IVec4;
overload extern function textureProj(sampler: ISampler2D, coords: Vec4): IVec4;
overload extern function textureProj(sampler: ISampler2D, coords: Vec3, bias: Float): IVec4;
overload extern function textureProj(sampler: ISampler2D, coords: Vec4, bias: Float): IVec4;
overload extern function textureProj(sampler: USampler2D, coords: Vec3): UVec4;
overload extern function textureProj(sampler: USampler2D, coords: Vec4): UVec4;
overload extern function textureProj(sampler: USampler2D, coords: Vec3, bias: Float): UVec4;
overload extern function textureProj(sampler: USampler2D, coords: Vec4, bias: Float): UVec4;
overload extern function textureProj(sampler: Sampler3D, coords: Vec4): Vec4;
overload extern function textureProj(sampler: Sampler3D, coords: Vec4, bias: Float): Vec4;
overload extern function textureProj(sampler: ISampler3D, coords: Vec4): IVec4;
overload extern function textureProj(sampler: ISampler3D, coords: Vec4, bias: Float): IVec4;
overload extern function textureProj(sampler: USampler3D, coords: Vec4): UVec4;
overload extern function textureProj(sampler: USampler3D, coords: Vec4, bias: Float): UVec4;
overload extern function textureLod(sampler: Sampler2D, coords: Vec2, lod: Float): Vec4;
overload extern function textureLod(sampler: ISampler2D, coords: Vec2, lod: Float): IVec4;
overload extern function textureLod(sampler: USampler2D, coords: Vec2, lod: Float): UVec4;
overload extern function textureLod(sampler: Sampler2DArray, coords: Vec3, lod: Float): Vec4;
overload extern function textureLod(sampler: ISampler2DArray, coords: Vec3, lod: Float): IVec4;
overload extern function textureLod(sampler: USampler2DArray, coords: Vec3, lod: Float): UVec4;
overload extern function textureLod(sampler: Sampler3D, coords: Vec3, lod: Float): Vec4;
overload extern function textureLod(sampler: ISampler3D, coords: Vec3, lod: Float): IVec4;
overload extern function textureLod(sampler: USampler3D, coords: Vec3, lod: Float): UVec4;
overload extern function textureLod(sampler: SamplerCube, coords: Vec3, lod: Float): Vec4;
overload extern function textureLod(sampler: SamplerCubeArray, coords: Vec4, lod: Float): Vec4;
overload extern function texelFetch(sampler: Sampler2D, coords: IVec2, lod: Int): Vec4;
overload extern function texelFetch(sampler: ISampler2D, coords: IVec2, lod: Int): IVec4;
overload extern function texelFetch(sampler: USampler2D, coords: IVec2, lod: Int): UVec4;
overload extern function texelFetch(sampler: Sampler2DArray, coords: IVec3, lod: Int): Vec4;
overload extern function texelFetch(sampler: ISampler2DArray, coords: IVec3, lod: Int): IVec4;
overload extern function texelFetch(sampler: USampler2DArray, coords: IVec3, lod: Int): UVec4;
overload extern function texelFetch(sampler: Sampler3D, coords: IVec3, lod: Int): Vec4;
overload extern function texelFetch(sampler: ISampler3D, coords: IVec3, lod: Int): IVec4;
overload extern function texelFetch(sampler: USampler3D, coords: IVec3, lod: Int): UVec4;
overload extern function textureProjLod(sampler: Sampler2D, coords: Vec3, lod: Float): Vec4;
overload extern function textureProjLod(sampler: Sampler2D, coords: Vec4, lod: Float): Vec4;
overload extern function textureProjLod(sampler: ISampler2D, coords: Vec3, lod: Float): IVec4;
overload extern function textureProjLod(sampler: ISampler2D, coords: Vec4, lod: Float): IVec4;
overload extern function textureProjLod(sampler: USampler2D, coords: Vec3, lod: Float): UVec4;
overload extern function textureProjLod(sampler: USampler2D, coords: Vec4, lod: Float): UVec4;
overload extern function textureProjLod(sampler: Sampler3D, coords: Vec4, lod: Float): Vec4;
overload extern function textureProjLod(sampler: ISampler3D, coords: Vec4, lod: Float): IVec4;
overload extern function textureProjLod(sampler: USampler3D, coords: Vec4, lod: Float): UVec4;
overload extern function textureGrad(sampler: Sampler2D, coords: Vec2, dPdx: Vec2, dPdy: Vec2): Vec4;
overload extern function textureGrad(sampler: ISampler2D, coords: Vec2, dPdx: Vec2, dPdy: Vec2): IVec4;
overload extern function textureGrad(sampler: USampler2D, coords: Vec2, dPdx: Vec2, dPdy: Vec2): UVec4;
overload extern function textureGrad(sampler: Sampler2DArray, coords: Vec3, dPdx: Vec2, dPdy: Vec2): Vec4;
overload extern function textureGrad(sampler: ISampler2DArray, coords: Vec3, dPdx: Vec2, dPdy: Vec2): IVec4;
overload extern function textureGrad(sampler: USampler2DArray, coords: Vec3, dPdx: Vec2, dPdy: Vec2): UVec4;
overload extern function textureGrad(sampler: Sampler3D, coords: Vec3, dPdx: Vec3, dPdy: Vec3): Vec4;
overload extern function textureGrad(sampler: ISampler3D, coords: Vec3, dPdx: Vec3, dPdy: Vec3): IVec4;
overload extern function textureGrad(sampler: USampler3D, coords: Vec3, dPdx: Vec3, dPdy: Vec3): UVec4;
overload extern function textureGrad(sampler: SamplerCube, coords: Vec3, dPdx: Vec3, dPdy: Vec3): Vec4;
overload extern function textureGrad(sampler: SamplerCubeArray, coords: Vec4, dPdx: Vec3, dPdy: Vec3): Vec4;
overload extern function textureProjGrad(sampler: Sampler2D, coords: Vec3, dPdx: Vec2, dPdy: Vec2): Vec4;
overload extern function textureProjGrad(sampler: Sampler2D, coords: Vec4, dPdx: Vec2, dPdy: Vec2): Vec4;
overload extern function textureProjGrad(sampler: ISampler2D, coords: Vec3, dPdx: Vec2, dPdy: Vec2): IVec4;
overload extern function textureProjGrad(sampler: ISampler2D, coords: Vec4, dPdx: Vec2, dPdy: Vec2): IVec4;
overload extern function textureProjGrad(sampler: USampler2D, coords: Vec3, dPdx: Vec2, dPdy: Vec2): UVec4;
overload extern function textureProjGrad(sampler: USampler2D, coords: Vec4, dPdx: Vec2, dPdy: Vec2): UVec4;
overload extern function textureProjGrad(sampler: Sampler3D, coords: Vec4, dPdx: Vec3, dPdy: Vec3): Vec4;
overload extern function textureProjGrad(sampler: ISampler3D, coords: Vec4, dPdx: Vec3, dPdy: Vec3): IVec4;
overload extern function textureProjGrad(sampler: USampler3D, coords: Vec4, dPdx: Vec3, dPdy: Vec3): UVec4;
overload extern function textureGather(sampler: Sampler2D, coords: Vec2): Vec4;
overload extern function textureGather(sampler: ISampler2D, coords: Vec2): IVec4;
overload extern function textureGather(sampler: USampler2D, coords: Vec2): UVec4;
overload extern function textureGather(sampler: Sampler2D, coords: Vec2, comp: Int): Vec4;
overload extern function textureGather(sampler: ISampler2D, coords: Vec2, comp: Int): IVec4;
overload extern function textureGather(sampler: USampler2D, coords: Vec2, comp: Int): UVec4;
overload extern function textureGather(sampler: Sampler2DArray, coords: Vec3): Vec4;
overload extern function textureGather(sampler: ISampler2DArray, coords: Vec3): IVec4;
overload extern function textureGather(sampler: USampler2DArray, coords: Vec3): UVec4;
overload extern function textureGather(sampler: Sampler2DArray, coords: Vec3, comp: Int): Vec4;
overload extern function textureGather(sampler: ISampler2DArray, coords: Vec3, comp: Int): IVec4;
overload extern function textureGather(sampler: USampler2DArray, coords: Vec3, comp: Int): UVec4;
overload extern function textureGather(sampler: SamplerCube, coords: Vec3): Vec4;
overload extern function textureGather(sampler: SamplerCube, coords: Vec3, comp: Int): Vec4;
overload extern function textureQueryLod(sampler: Sampler2D, coords: Vec2): Vec2;
overload extern function textureQueryLod(sampler: ISampler2D, coords: Vec2): Vec2;
overload extern function textureQueryLod(sampler: USampler2D, coords: Vec2): Vec2;
overload extern function textureQueryLod(sampler: Sampler2DArray, coords: Vec2): Vec2;
overload extern function textureQueryLod(sampler: ISampler2DArray, coords: Vec2): Vec2;
overload extern function textureQueryLod(sampler: USampler2DArray, coords: Vec2): Vec2;
overload extern function textureQueryLod(sampler: Sampler3D, coords: Vec3): Vec2;
overload extern function textureQueryLod(sampler: ISampler3D, coords: Vec3): Vec2;
overload extern function textureQueryLod(sampler: USampler3D, coords: Vec3): Vec2;
overload extern function textureQueryLod(sampler: SamplerCube, coords: Vec3): Vec2;
overload extern function textureQueryLevels(sampler: Sampler2D): Int;
overload extern function textureQueryLevels(sampler: ISampler2D): Int;
overload extern function textureQueryLevels(sampler: USampler2D): Int;
overload extern function textureQueryLevels(sampler: Sampler2DArray): Int;
overload extern function textureQueryLevels(sampler: ISampler2DArray): Int;
overload extern function textureQueryLevels(sampler: USampler2DArray): Int;
overload extern function textureQueryLevels(sampler: Sampler3D): Int;
overload extern function textureQueryLevels(sampler: ISampler3D): Int;
overload extern function textureQueryLevels(sampler: USampler3D): Int;
overload extern function textureQueryLevels(sampler: SamplerCube): Int;
overload extern function dFdx(p: Float): Float;
overload extern function dFdx(p: Vec2): Vec2;
overload extern function dFdx(p: Vec3): Vec3;
overload extern function dFdx(p: Vec4): Vec4;
overload extern function dFdxCoarse(p: Float): Float;
overload extern function dFdxCoarse(p: Vec2): Vec2;
overload extern function dFdxCoarse(p: Vec3): Vec3;
overload extern function dFdxCoarse(p: Vec4): Vec4;
overload extern function dFdxFine(p: Float): Float;
overload extern function dFdxFine(p: Vec2): Vec2;
overload extern function dFdxFine(p: Vec3): Vec3;
overload extern function dFdxFine(p: Vec4): Vec4;
overload extern function dFdy(p: Float): Float;
overload extern function dFdy(p: Vec2): Vec2;
overload extern function dFdy(p: Vec3): Vec3;
overload extern function dFdy(p: Vec4): Vec4;
overload extern function dFdyCoarse(p: Float): Float;
overload extern function dFdyCoarse(p: Vec2): Vec2;
overload extern function dFdyCoarse(p: Vec3): Vec3;
overload extern function dFdyCoarse(p: Vec4): Vec4;
overload extern function dFdyFine(p: Float): Float;
overload extern function dFdyFine(p: Vec2): Vec2;
overload extern function dFdyFine(p: Vec3): Vec3;
overload extern function dFdyFine(p: Vec4): Vec4;
overload extern function fwidth(p: Float): Float;
overload extern function fwidth(p: Vec2): Vec2;
overload extern function fwidth(p: Vec3): Vec3;
overload extern function fwidth(p: Vec4): Vec4;
overload extern function fwidthCoarse(p: Float): Float;
overload extern function fwidthCoarse(p: Vec2): Vec2;
overload extern function fwidthCoarse(p: Vec3): Vec3;
overload extern function fwidthCoarse(p: Vec4): Vec4;
overload extern function fwidthFine(p: Float): Float;
overload extern function fwidthFine(p: Vec2): Vec2;
overload extern function fwidthFine(p: Vec3): Vec3;
overload extern function fwidthFine(p: Vec4): Vec4;
overload extern function fma(a: Float, b: Float, c: Float): Float;
overload extern function fma(a: Vec2, b: Vec2, c: Vec2): Vec2;
overload extern function fma(a: Vec3, b: Vec3, c: Vec3): Vec3;
overload extern function fma(a: Vec4, b: Vec4, c: Vec4): Vec4;
extern function packHalf2x16(v: Vec2): UInt;
extern function packUnorm2x16(v: Vec2): UInt;
extern function packSnorm2x16(v: Vec2): UInt;
extern function packUnorm4x8(v: Vec4): UInt;
extern function packSnorm4x8(v: Vec4): UInt;
extern function unpackHalf2x16(v: UInt): Vec2;
extern function unpackUnorm2x16(v: UInt): Vec2;
extern function unpackSnorm2x16(v: UInt): Vec2;
extern function unpackUnorm4x8(v: UInt): Vec4;
extern function unpackSnorm4x8(v: UInt): Vec4;
overload extern function bitfieldExtract(value: Int, offset: Int, bits: Int): Int;
overload extern function bitfieldExtract(value: IVec2, offset: Int, bits: Int): IVec2;
overload extern function bitfieldExtract(value: IVec3, offset: Int, bits: Int): IVec3;
overload extern function bitfieldExtract(value: IVec4, offset: Int, bits: Int): IVec4;
overload extern function bitfieldExtract(value: UInt, offset: Int, bits: Int): UInt;
overload extern function bitfieldExtract(value: UVec2, offset: Int, bits: Int): UVec2;
overload extern function bitfieldExtract(value: UVec3, offset: Int, bits: Int): UVec3;
overload extern function bitfieldExtract(value: UVec4, offset: Int, bits: Int): UVec4;
overload extern function bitfieldInsert(base: Int, insert: Int, offset: Int, bits: Int): Int;
overload extern function bitfieldInsert(base: IVec2, insert: IVec2, offset: Int, bits: Int): IVec2;
overload extern function bitfieldInsert(base: IVec3, insert: IVec3, offset: Int, bits: Int): IVec3;
overload extern function bitfieldInsert(base: IVec4, insert: IVec4, offset: Int, bits: Int): IVec4;
overload extern function bitfieldInsert(base: UInt, insert: UInt, offset: Int, bits: Int): UInt;
overload extern function bitfieldInsert(base: UVec2, insert: UVec2, offset: Int, bits: Int): UVec2;
overload extern function bitfieldInsert(base: UVec3, insert: UVec3, offset: Int, bits: Int): UVec3;
overload extern function bitfieldInsert(base: UVec4, insert: UVec4, offset: Int, bits: Int): UVec4;
overload extern function bitfieldReverse(value: Int): Int;
overload extern function bitfieldReverse(value: IVec2): IVec2;
overload extern function bitfieldReverse(value: IVec3): IVec3;
overload extern function bitfieldReverse(value: IVec4): IVec4;
overload extern function bitfieldReverse(value: UInt): UInt;
overload extern function bitfieldReverse(value: UVec2): UVec2;
overload extern function bitfieldReverse(value: UVec3): UVec3;
overload extern function bitfieldReverse(value: UVec4): UVec4;
overload extern function bitCount(value: Int): Int;
overload extern function bitCount(value: IVec2): IVec2;
overload extern function bitCount(value: IVec3): IVec3;
overload extern function bitCount(value: IVec4): IVec4;
overload extern function bitCount(value: UInt): UInt;
overload extern function bitCount(value: UVec2): UVec2;
overload extern function bitCount(value: UVec3): UVec3;
overload extern function bitCount(value: UVec4): UVec4;
overload extern function findLSB(value: Int): Int;
overload extern function findLSB(value: IVec2): IVec2;
overload extern function findLSB(value: IVec3): IVec3;
overload extern function findLSB(value: IVec4): IVec4;
overload extern function findLSB(value: UInt): UInt;
overload extern function findLSB(value: UVec2): UVec2;
overload extern function findLSB(value: UVec3): UVec3;
overload extern function findLSB(value: UVec4): UVec4;
overload extern function findMSB(value: Int): Int;
overload extern function findMSB(value: IVec2): IVec2;
overload extern function findMSB(value: IVec3): IVec3;
overload extern function findMSB(value: IVec4): IVec4;
overload extern function findMSB(value: UInt): UInt;
overload extern function findMSB(value: UVec2): UVec2;
overload extern function findMSB(value: UVec3): UVec3;
overload extern function findMSB(value: UVec4): UVec4;
overload extern function umulExtended(x: UInt, y: UInt, msb: UInt, lsb: UInt): Void;
overload extern function umulExtended(x: UVec2, y: UVec2, msb: UVec2, lsb: UVec2): Void;
overload extern function umulExtended(x: UVec3, y: UVec3, msb: UVec3, lsb: UVec3): Void;
overload extern function umulExtended(x: UVec4, y: UVec4, msb: UVec4, lsb: UVec4): Void;
overload extern function imulExtended(x: Int, y: Int, msb: Int, lsb: Int): Void;
overload extern function imulExtended(x: IVec2, y: IVec2, msb: IVec2, lsb: IVec2): Void;
overload extern function imulExtended(x: IVec3, y: IVec3, msb: IVec3, lsb: IVec3): Void;
overload extern function imulExtended(x: IVec4, y: IVec4, msb: IVec4, lsb: IVec4): Void;
overload extern function uaddCarry(x: UInt, y: UInt, carry: UInt): UInt;
overload extern function uaddCarry(x: UVec2, y: UVec2, carry: UVec2): UVec2;
overload extern function uaddCarry(x: UVec3, y: UVec3, carry: UVec3): UVec3;
overload extern function uaddCarry(x: UVec4, y: UVec4, carry: UVec4): UVec4;
overload extern function usubBorrow(x: UInt, y: UInt, borrow: UInt): UInt;
overload extern function usubBorrow(x: UVec2, y: UVec2, borrow: UVec2): UVec2;
overload extern function usubBorrow(x: UVec3, y: UVec3, borrow: UVec3): UVec3;
overload extern function usubBorrow(x: UVec4, y: UVec4, borrow: UVec4): UVec4;
overload extern function ldexp(x: Float, exp: Int): Float;
overload extern function ldexp(x: Vec2, exp: IVec2): Vec2;
overload extern function ldexp(x: Vec3, exp: IVec3): Vec3;
overload extern function ldexp(x: Vec4, exp: IVec4): Vec4;
overload extern function frexp(x: Float, exp: Int): Float;
overload extern function frexp(x: Vec2, exp: IVec2): Vec2;
overload extern function frexp(x: Vec3, exp: IVec3): Vec3;
overload extern function frexp(x: Vec4, exp: IVec4): Vec4;
