package gdshader.types;

import gdshader.types.*;

@:copyValue
@:noCompletion
@:avoidTemporaries
@:gdshaderType("ivec3")
extern class IVec3Inner {
	var x: Int;
	var y: Int;
	var z: Int;
	var xx: IVec2;
	var xy: IVec2;
	var xz: IVec2;
	var yx: IVec2;
	var yy: IVec2;
	var yz: IVec2;
	var zx: IVec2;
	var zy: IVec2;
	var zz: IVec2;
	var xxx: IVec3;
	var xxy: IVec3;
	var xxz: IVec3;
	var xyx: IVec3;
	var xyy: IVec3;
	var xyz: IVec3;
	var xzx: IVec3;
	var xzy: IVec3;
	var xzz: IVec3;
	var yxx: IVec3;
	var yxy: IVec3;
	var yxz: IVec3;
	var yyx: IVec3;
	var yyy: IVec3;
	var yyz: IVec3;
	var yzx: IVec3;
	var yzy: IVec3;
	var yzz: IVec3;
	var zxx: IVec3;
	var zxy: IVec3;
	var zxz: IVec3;
	var zyx: IVec3;
	var zyy: IVec3;
	var zyz: IVec3;
	var zzx: IVec3;
	var zzy: IVec3;
	var zzz: IVec3;
	var xxxx: IVec4;
	var xxxy: IVec4;
	var xxxz: IVec4;
	var xxyx: IVec4;
	var xxyy: IVec4;
	var xxyz: IVec4;
	var xxzx: IVec4;
	var xxzy: IVec4;
	var xxzz: IVec4;
	var xyxx: IVec4;
	var xyxy: IVec4;
	var xyxz: IVec4;
	var xyyx: IVec4;
	var xyyy: IVec4;
	var xyyz: IVec4;
	var xyzx: IVec4;
	var xyzy: IVec4;
	var xyzz: IVec4;
	var xzxx: IVec4;
	var xzxy: IVec4;
	var xzxz: IVec4;
	var xzyx: IVec4;
	var xzyy: IVec4;
	var xzyz: IVec4;
	var xzzx: IVec4;
	var xzzy: IVec4;
	var xzzz: IVec4;
	var yxxx: IVec4;
	var yxxy: IVec4;
	var yxxz: IVec4;
	var yxyx: IVec4;
	var yxyy: IVec4;
	var yxyz: IVec4;
	var yxzx: IVec4;
	var yxzy: IVec4;
	var yxzz: IVec4;
	var yyxx: IVec4;
	var yyxy: IVec4;
	var yyxz: IVec4;
	var yyyx: IVec4;
	var yyyy: IVec4;
	var yyyz: IVec4;
	var yyzx: IVec4;
	var yyzy: IVec4;
	var yyzz: IVec4;
	var yzxx: IVec4;
	var yzxy: IVec4;
	var yzxz: IVec4;
	var yzyx: IVec4;
	var yzyy: IVec4;
	var yzyz: IVec4;
	var yzzx: IVec4;
	var yzzy: IVec4;
	var yzzz: IVec4;
	var zxxx: IVec4;
	var zxxy: IVec4;
	var zxxz: IVec4;
	var zxyx: IVec4;
	var zxyy: IVec4;
	var zxyz: IVec4;
	var zxzx: IVec4;
	var zxzy: IVec4;
	var zxzz: IVec4;
	var zyxx: IVec4;
	var zyxy: IVec4;
	var zyxz: IVec4;
	var zyyx: IVec4;
	var zyyy: IVec4;
	var zyyz: IVec4;
	var zyzx: IVec4;
	var zyzy: IVec4;
	var zyzz: IVec4;
	var zzxx: IVec4;
	var zzxy: IVec4;
	var zzxz: IVec4;
	var zzyx: IVec4;
	var zzyy: IVec4;
	var zzyz: IVec4;
	var zzzx: IVec4;
	var zzzy: IVec4;
	var zzzz: IVec4;
	var r: Int;
	var g: Int;
	var b: Int;
	var rr: IVec2;
	var rg: IVec2;
	var rb: IVec2;
	var gr: IVec2;
	var gg: IVec2;
	var gb: IVec2;
	var br: IVec2;
	var bg: IVec2;
	var bb: IVec2;
	var rrr: IVec3;
	var rrg: IVec3;
	var rrb: IVec3;
	var rgr: IVec3;
	var rgg: IVec3;
	var rgb: IVec3;
	var rbr: IVec3;
	var rbg: IVec3;
	var rbb: IVec3;
	var grr: IVec3;
	var grg: IVec3;
	var grb: IVec3;
	var ggr: IVec3;
	var ggg: IVec3;
	var ggb: IVec3;
	var gbr: IVec3;
	var gbg: IVec3;
	var gbb: IVec3;
	var brr: IVec3;
	var brg: IVec3;
	var brb: IVec3;
	var bgr: IVec3;
	var bgg: IVec3;
	var bgb: IVec3;
	var bbr: IVec3;
	var bbg: IVec3;
	var bbb: IVec3;
	var rrrr: IVec4;
	var rrrg: IVec4;
	var rrrb: IVec4;
	var rrgr: IVec4;
	var rrgg: IVec4;
	var rrgb: IVec4;
	var rrbr: IVec4;
	var rrbg: IVec4;
	var rrbb: IVec4;
	var rgrr: IVec4;
	var rgrg: IVec4;
	var rgrb: IVec4;
	var rggr: IVec4;
	var rggg: IVec4;
	var rggb: IVec4;
	var rgbr: IVec4;
	var rgbg: IVec4;
	var rgbb: IVec4;
	var rbrr: IVec4;
	var rbrg: IVec4;
	var rbrb: IVec4;
	var rbgr: IVec4;
	var rbgg: IVec4;
	var rbgb: IVec4;
	var rbbr: IVec4;
	var rbbg: IVec4;
	var rbbb: IVec4;
	var grrr: IVec4;
	var grrg: IVec4;
	var grrb: IVec4;
	var grgr: IVec4;
	var grgg: IVec4;
	var grgb: IVec4;
	var grbr: IVec4;
	var grbg: IVec4;
	var grbb: IVec4;
	var ggrr: IVec4;
	var ggrg: IVec4;
	var ggrb: IVec4;
	var gggr: IVec4;
	var gggg: IVec4;
	var gggb: IVec4;
	var ggbr: IVec4;
	var ggbg: IVec4;
	var ggbb: IVec4;
	var gbrr: IVec4;
	var gbrg: IVec4;
	var gbrb: IVec4;
	var gbgr: IVec4;
	var gbgg: IVec4;
	var gbgb: IVec4;
	var gbbr: IVec4;
	var gbbg: IVec4;
	var gbbb: IVec4;
	var brrr: IVec4;
	var brrg: IVec4;
	var brrb: IVec4;
	var brgr: IVec4;
	var brgg: IVec4;
	var brgb: IVec4;
	var brbr: IVec4;
	var brbg: IVec4;
	var brbb: IVec4;
	var bgrr: IVec4;
	var bgrg: IVec4;
	var bgrb: IVec4;
	var bggr: IVec4;
	var bggg: IVec4;
	var bggb: IVec4;
	var bgbr: IVec4;
	var bgbg: IVec4;
	var bgbb: IVec4;
	var bbrr: IVec4;
	var bbrg: IVec4;
	var bbrb: IVec4;
	var bbgr: IVec4;
	var bbgg: IVec4;
	var bbgb: IVec4;
	var bbbr: IVec4;
	var bbbg: IVec4;
	var bbbb: IVec4;
	var s: Int;
	var t: Int;
	var p: Int;
	var ss: IVec2;
	var st: IVec2;
	var sp: IVec2;
	var ts: IVec2;
	var tt: IVec2;
	var tp: IVec2;
	var ps: IVec2;
	var pt: IVec2;
	var pp: IVec2;
	var sss: IVec3;
	var sst: IVec3;
	var ssp: IVec3;
	var sts: IVec3;
	var stt: IVec3;
	var stp: IVec3;
	var sps: IVec3;
	var spt: IVec3;
	var spp: IVec3;
	var tss: IVec3;
	var tst: IVec3;
	var tsp: IVec3;
	var tts: IVec3;
	var ttt: IVec3;
	var ttp: IVec3;
	var tps: IVec3;
	var tpt: IVec3;
	var tpp: IVec3;
	var pss: IVec3;
	var pst: IVec3;
	var psp: IVec3;
	var pts: IVec3;
	var ptt: IVec3;
	var ptp: IVec3;
	var pps: IVec3;
	var ppt: IVec3;
	var ppp: IVec3;
	var ssss: IVec4;
	var ssst: IVec4;
	var sssp: IVec4;
	var ssts: IVec4;
	var sstt: IVec4;
	var sstp: IVec4;
	var ssps: IVec4;
	var sspt: IVec4;
	var sspp: IVec4;
	var stss: IVec4;
	var stst: IVec4;
	var stsp: IVec4;
	var stts: IVec4;
	var sttt: IVec4;
	var sttp: IVec4;
	var stps: IVec4;
	var stpt: IVec4;
	var stpp: IVec4;
	var spss: IVec4;
	var spst: IVec4;
	var spsp: IVec4;
	var spts: IVec4;
	var sptt: IVec4;
	var sptp: IVec4;
	var spps: IVec4;
	var sppt: IVec4;
	var sppp: IVec4;
	var tsss: IVec4;
	var tsst: IVec4;
	var tssp: IVec4;
	var tsts: IVec4;
	var tstt: IVec4;
	var tstp: IVec4;
	var tsps: IVec4;
	var tspt: IVec4;
	var tspp: IVec4;
	var ttss: IVec4;
	var ttst: IVec4;
	var ttsp: IVec4;
	var ttts: IVec4;
	var tttt: IVec4;
	var tttp: IVec4;
	var ttps: IVec4;
	var ttpt: IVec4;
	var ttpp: IVec4;
	var tpss: IVec4;
	var tpst: IVec4;
	var tpsp: IVec4;
	var tpts: IVec4;
	var tptt: IVec4;
	var tptp: IVec4;
	var tpps: IVec4;
	var tppt: IVec4;
	var tppp: IVec4;
	var psss: IVec4;
	var psst: IVec4;
	var pssp: IVec4;
	var psts: IVec4;
	var pstt: IVec4;
	var pstp: IVec4;
	var psps: IVec4;
	var pspt: IVec4;
	var pspp: IVec4;
	var ptss: IVec4;
	var ptst: IVec4;
	var ptsp: IVec4;
	var ptts: IVec4;
	var pttt: IVec4;
	var pttp: IVec4;
	var ptps: IVec4;
	var ptpt: IVec4;
	var ptpp: IVec4;
	var ppss: IVec4;
	var ppst: IVec4;
	var ppsp: IVec4;
	var ppts: IVec4;
	var pptt: IVec4;
	var pptp: IVec4;
	var ppps: IVec4;
	var pppt: IVec4;
	var pppp: IVec4;
}

@:forward
@:copyValue
@:avoidTemporaries
@:gdshaderType("ivec3")
extern abstract IVec3(IVec3Inner) {
	@:overload(function(x: Int, y: Int, z: Int): Void {})
	@:overload(function(ivec2: IVec2, int: Int): Void {})
	@:overload(function(int: Int, ivec2: IVec2): Void {})
	@:overload(function(bvec3: BVec3): Void {})
	@:overload(function(ivec3: IVec3): Void {})
	@:overload(function(uvec3: UVec3): Void {})
	@:overload(function(vec3: Vec3): Void {})
	@:native("ivec3")
	public function new(int: Int);

	@:op(A == B) public static inline function equalsIVec3(me: IVec3, other: IVec3): Bool return untyped __gdshader__("({0} == {1})", me, other);
	@:op(A != B) public static inline function notEqualsIVec3(me: IVec3, other: IVec3): Bool return untyped __gdshader__("({0} != {1})", me, other);
	@:op(-A) public static inline function negate(me: IVec3): IVec3 return untyped __gdshader__("(-{0})", me);
	@:op(A + B) public static inline function addInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} + {1})", me, other);
	@:op(A + B) public static inline function addIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} + {1})", me, other);
	@:op(A - B) public static inline function subtractInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} - {1})", me, other);
	@:op(A - B) public static inline function subtractIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} - {1})", me, other);
	@:op(A * B) public static inline function multiplyInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} * {1})", me, other);
	@:op(A * B) public static inline function multiplyIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} * {1})", me, other);
	@:op(A / B) public static inline function divideInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} / {1})", me, other);
	@:op(A / B) public static inline function divideIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} / {1})", me, other);
	@:op(A % B) public static inline function modulusInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} % {1})", me, other);
	@:op(A % B) public static inline function modulusIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} % {1})", me, other);
	@:op(A << B) public static inline function shiftLeftInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} << {1})", me, other);
	@:op(A << B) public static inline function shiftLeftIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} << {1})", me, other);
	@:op(A >> B) public static inline function shiftRightInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} >> {1})", me, other);
	@:op(A >> B) public static inline function shiftRightIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} >> {1})", me, other);
	@:op(A += B) public static inline function addAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} += {1})", me, other);
	@:op(A += B) public static inline function addAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} += {1})", me, other);
	@:op(A -= B) public static inline function subtractAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} -= {1})", me, other);
	@:op(A -= B) public static inline function subtractAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} -= {1})", me, other);
	@:op(A *= B) public static inline function multiplyAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} *= {1})", me, other);
	@:op(A *= B) public static inline function multiplyAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} *= {1})", me, other);
	@:op(A /= B) public static inline function divideAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} /= {1})", me, other);
	@:op(A /= B) public static inline function divideAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} /= {1})", me, other);
	@:op(A %= B) public static inline function modulusAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} %= {1})", me, other);
	@:op(A %= B) public static inline function modulusAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} %= {1})", me, other);
	@:op(A <<= B) public static inline function shiftLeftAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} <<= {1})", me, other);
	@:op(A <<= B) public static inline function shiftLeftAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} <<= {1})", me, other);
	@:op(A >>= B) public static inline function shiftRightAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} >>= {1})", me, other);
	@:op(A >>= B) public static inline function shiftRightAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} >>= {1})", me, other);
	@:op(A &= B) public static inline function bitAndAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} &= {1})", me, other);
	@:op(A &= B) public static inline function bitAndAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} &= {1})", me, other);
	@:op(A |= B) public static inline function bitOrAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} |= {1})", me, other);
	@:op(A |= B) public static inline function bitOrAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} |= {1})", me, other);
	@:op(A ^= B) public static inline function bitXOrAssignInt(me: IVec3, other: Int): IVec3 return untyped __gdshader__("({0} ^= {1})", me, other);
	@:op(A ^= B) public static inline function bitXOrAssignIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} ^= {1})", me, other);
	@:op(A & B) public static inline function bitAndIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} & {1})", me, other);
	@:op(A | B) public static inline function bitOrIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} | {1})", me, other);
	@:op(A ^ B) public static inline function bitXOrIVec3(me: IVec3, other: IVec3): IVec3 return untyped __gdshader__("({0} ^ {1})", me, other);
	@:op(~A) public static inline function bitInvert(me: IVec3): IVec3 return untyped __gdshader__("(~{0})", me);
	@:op(++A) public static inline function increment(me: IVec3): IVec3 return untyped __gdshader__("(++{0})", me);
	@:op(--A) public static inline function decrement(me: IVec3): IVec3 return untyped __gdshader__("(--{0})", me);
	@:op(A++) public static inline function postIncrement(me: IVec3): IVec3 return untyped __gdshader__("({0}++)", me);
	@:op(A--) public static inline function postDecrement(me: IVec3): IVec3 return untyped __gdshader__("({0}--)", me);
	@:op(A + B) public static inline function addIntFlipped(other: Int, me: IVec3): IVec3 return untyped __gdshader__("({0} + {1})", other, me);
	@:op(A - B) public static inline function subtractIntFlipped(other: Int, me: IVec3): IVec3 return untyped __gdshader__("({0} - {1})", other, me);
	@:op(A * B) public static inline function multiplyIntFlipped(other: Int, me: IVec3): IVec3 return untyped __gdshader__("({0} * {1})", other, me);
	@:op(A / B) public static inline function divideIntFlipped(other: Int, me: IVec3): IVec3 return untyped __gdshader__("({0} / {1})", other, me);
}
