package gdshader.types;

import gdshader.types.*;

@:copyValue
@:noCompletion
@:avoidTemporaries
@:gdshaderType("uvec3")
extern class UVec3Inner {
	var x: UInt;
	var y: UInt;
	var z: UInt;
	var xx: UVec2;
	var xy: UVec2;
	var xz: UVec2;
	var yx: UVec2;
	var yy: UVec2;
	var yz: UVec2;
	var zx: UVec2;
	var zy: UVec2;
	var zz: UVec2;
	var xxx: UVec3;
	var xxy: UVec3;
	var xxz: UVec3;
	var xyx: UVec3;
	var xyy: UVec3;
	var xyz: UVec3;
	var xzx: UVec3;
	var xzy: UVec3;
	var xzz: UVec3;
	var yxx: UVec3;
	var yxy: UVec3;
	var yxz: UVec3;
	var yyx: UVec3;
	var yyy: UVec3;
	var yyz: UVec3;
	var yzx: UVec3;
	var yzy: UVec3;
	var yzz: UVec3;
	var zxx: UVec3;
	var zxy: UVec3;
	var zxz: UVec3;
	var zyx: UVec3;
	var zyy: UVec3;
	var zyz: UVec3;
	var zzx: UVec3;
	var zzy: UVec3;
	var zzz: UVec3;
	var xxxx: UVec4;
	var xxxy: UVec4;
	var xxxz: UVec4;
	var xxyx: UVec4;
	var xxyy: UVec4;
	var xxyz: UVec4;
	var xxzx: UVec4;
	var xxzy: UVec4;
	var xxzz: UVec4;
	var xyxx: UVec4;
	var xyxy: UVec4;
	var xyxz: UVec4;
	var xyyx: UVec4;
	var xyyy: UVec4;
	var xyyz: UVec4;
	var xyzx: UVec4;
	var xyzy: UVec4;
	var xyzz: UVec4;
	var xzxx: UVec4;
	var xzxy: UVec4;
	var xzxz: UVec4;
	var xzyx: UVec4;
	var xzyy: UVec4;
	var xzyz: UVec4;
	var xzzx: UVec4;
	var xzzy: UVec4;
	var xzzz: UVec4;
	var yxxx: UVec4;
	var yxxy: UVec4;
	var yxxz: UVec4;
	var yxyx: UVec4;
	var yxyy: UVec4;
	var yxyz: UVec4;
	var yxzx: UVec4;
	var yxzy: UVec4;
	var yxzz: UVec4;
	var yyxx: UVec4;
	var yyxy: UVec4;
	var yyxz: UVec4;
	var yyyx: UVec4;
	var yyyy: UVec4;
	var yyyz: UVec4;
	var yyzx: UVec4;
	var yyzy: UVec4;
	var yyzz: UVec4;
	var yzxx: UVec4;
	var yzxy: UVec4;
	var yzxz: UVec4;
	var yzyx: UVec4;
	var yzyy: UVec4;
	var yzyz: UVec4;
	var yzzx: UVec4;
	var yzzy: UVec4;
	var yzzz: UVec4;
	var zxxx: UVec4;
	var zxxy: UVec4;
	var zxxz: UVec4;
	var zxyx: UVec4;
	var zxyy: UVec4;
	var zxyz: UVec4;
	var zxzx: UVec4;
	var zxzy: UVec4;
	var zxzz: UVec4;
	var zyxx: UVec4;
	var zyxy: UVec4;
	var zyxz: UVec4;
	var zyyx: UVec4;
	var zyyy: UVec4;
	var zyyz: UVec4;
	var zyzx: UVec4;
	var zyzy: UVec4;
	var zyzz: UVec4;
	var zzxx: UVec4;
	var zzxy: UVec4;
	var zzxz: UVec4;
	var zzyx: UVec4;
	var zzyy: UVec4;
	var zzyz: UVec4;
	var zzzx: UVec4;
	var zzzy: UVec4;
	var zzzz: UVec4;
	var r: UInt;
	var g: UInt;
	var b: UInt;
	var rr: UVec2;
	var rg: UVec2;
	var rb: UVec2;
	var gr: UVec2;
	var gg: UVec2;
	var gb: UVec2;
	var br: UVec2;
	var bg: UVec2;
	var bb: UVec2;
	var rrr: UVec3;
	var rrg: UVec3;
	var rrb: UVec3;
	var rgr: UVec3;
	var rgg: UVec3;
	var rgb: UVec3;
	var rbr: UVec3;
	var rbg: UVec3;
	var rbb: UVec3;
	var grr: UVec3;
	var grg: UVec3;
	var grb: UVec3;
	var ggr: UVec3;
	var ggg: UVec3;
	var ggb: UVec3;
	var gbr: UVec3;
	var gbg: UVec3;
	var gbb: UVec3;
	var brr: UVec3;
	var brg: UVec3;
	var brb: UVec3;
	var bgr: UVec3;
	var bgg: UVec3;
	var bgb: UVec3;
	var bbr: UVec3;
	var bbg: UVec3;
	var bbb: UVec3;
	var rrrr: UVec4;
	var rrrg: UVec4;
	var rrrb: UVec4;
	var rrgr: UVec4;
	var rrgg: UVec4;
	var rrgb: UVec4;
	var rrbr: UVec4;
	var rrbg: UVec4;
	var rrbb: UVec4;
	var rgrr: UVec4;
	var rgrg: UVec4;
	var rgrb: UVec4;
	var rggr: UVec4;
	var rggg: UVec4;
	var rggb: UVec4;
	var rgbr: UVec4;
	var rgbg: UVec4;
	var rgbb: UVec4;
	var rbrr: UVec4;
	var rbrg: UVec4;
	var rbrb: UVec4;
	var rbgr: UVec4;
	var rbgg: UVec4;
	var rbgb: UVec4;
	var rbbr: UVec4;
	var rbbg: UVec4;
	var rbbb: UVec4;
	var grrr: UVec4;
	var grrg: UVec4;
	var grrb: UVec4;
	var grgr: UVec4;
	var grgg: UVec4;
	var grgb: UVec4;
	var grbr: UVec4;
	var grbg: UVec4;
	var grbb: UVec4;
	var ggrr: UVec4;
	var ggrg: UVec4;
	var ggrb: UVec4;
	var gggr: UVec4;
	var gggg: UVec4;
	var gggb: UVec4;
	var ggbr: UVec4;
	var ggbg: UVec4;
	var ggbb: UVec4;
	var gbrr: UVec4;
	var gbrg: UVec4;
	var gbrb: UVec4;
	var gbgr: UVec4;
	var gbgg: UVec4;
	var gbgb: UVec4;
	var gbbr: UVec4;
	var gbbg: UVec4;
	var gbbb: UVec4;
	var brrr: UVec4;
	var brrg: UVec4;
	var brrb: UVec4;
	var brgr: UVec4;
	var brgg: UVec4;
	var brgb: UVec4;
	var brbr: UVec4;
	var brbg: UVec4;
	var brbb: UVec4;
	var bgrr: UVec4;
	var bgrg: UVec4;
	var bgrb: UVec4;
	var bggr: UVec4;
	var bggg: UVec4;
	var bggb: UVec4;
	var bgbr: UVec4;
	var bgbg: UVec4;
	var bgbb: UVec4;
	var bbrr: UVec4;
	var bbrg: UVec4;
	var bbrb: UVec4;
	var bbgr: UVec4;
	var bbgg: UVec4;
	var bbgb: UVec4;
	var bbbr: UVec4;
	var bbbg: UVec4;
	var bbbb: UVec4;
	var s: UInt;
	var t: UInt;
	var p: UInt;
	var ss: UVec2;
	var st: UVec2;
	var sp: UVec2;
	var ts: UVec2;
	var tt: UVec2;
	var tp: UVec2;
	var ps: UVec2;
	var pt: UVec2;
	var pp: UVec2;
	var sss: UVec3;
	var sst: UVec3;
	var ssp: UVec3;
	var sts: UVec3;
	var stt: UVec3;
	var stp: UVec3;
	var sps: UVec3;
	var spt: UVec3;
	var spp: UVec3;
	var tss: UVec3;
	var tst: UVec3;
	var tsp: UVec3;
	var tts: UVec3;
	var ttt: UVec3;
	var ttp: UVec3;
	var tps: UVec3;
	var tpt: UVec3;
	var tpp: UVec3;
	var pss: UVec3;
	var pst: UVec3;
	var psp: UVec3;
	var pts: UVec3;
	var ptt: UVec3;
	var ptp: UVec3;
	var pps: UVec3;
	var ppt: UVec3;
	var ppp: UVec3;
	var ssss: UVec4;
	var ssst: UVec4;
	var sssp: UVec4;
	var ssts: UVec4;
	var sstt: UVec4;
	var sstp: UVec4;
	var ssps: UVec4;
	var sspt: UVec4;
	var sspp: UVec4;
	var stss: UVec4;
	var stst: UVec4;
	var stsp: UVec4;
	var stts: UVec4;
	var sttt: UVec4;
	var sttp: UVec4;
	var stps: UVec4;
	var stpt: UVec4;
	var stpp: UVec4;
	var spss: UVec4;
	var spst: UVec4;
	var spsp: UVec4;
	var spts: UVec4;
	var sptt: UVec4;
	var sptp: UVec4;
	var spps: UVec4;
	var sppt: UVec4;
	var sppp: UVec4;
	var tsss: UVec4;
	var tsst: UVec4;
	var tssp: UVec4;
	var tsts: UVec4;
	var tstt: UVec4;
	var tstp: UVec4;
	var tsps: UVec4;
	var tspt: UVec4;
	var tspp: UVec4;
	var ttss: UVec4;
	var ttst: UVec4;
	var ttsp: UVec4;
	var ttts: UVec4;
	var tttt: UVec4;
	var tttp: UVec4;
	var ttps: UVec4;
	var ttpt: UVec4;
	var ttpp: UVec4;
	var tpss: UVec4;
	var tpst: UVec4;
	var tpsp: UVec4;
	var tpts: UVec4;
	var tptt: UVec4;
	var tptp: UVec4;
	var tpps: UVec4;
	var tppt: UVec4;
	var tppp: UVec4;
	var psss: UVec4;
	var psst: UVec4;
	var pssp: UVec4;
	var psts: UVec4;
	var pstt: UVec4;
	var pstp: UVec4;
	var psps: UVec4;
	var pspt: UVec4;
	var pspp: UVec4;
	var ptss: UVec4;
	var ptst: UVec4;
	var ptsp: UVec4;
	var ptts: UVec4;
	var pttt: UVec4;
	var pttp: UVec4;
	var ptps: UVec4;
	var ptpt: UVec4;
	var ptpp: UVec4;
	var ppss: UVec4;
	var ppst: UVec4;
	var ppsp: UVec4;
	var ppts: UVec4;
	var pptt: UVec4;
	var pptp: UVec4;
	var ppps: UVec4;
	var pppt: UVec4;
	var pppp: UVec4;
}

@:forward
@:copyValue
@:avoidTemporaries
@:gdshaderType("uvec3")
extern abstract UVec3(UVec3Inner) {
	@:overload(function(x: UInt, y: UInt, z: UInt): Void {})
	@:overload(function(uvec2: UVec2, uint: UInt): Void {})
	@:overload(function(uint: UInt, uvec2: UVec2): Void {})
	@:overload(function(bvec3: BVec3): Void {})
	@:overload(function(ivec3: IVec3): Void {})
	@:overload(function(uvec3: UVec3): Void {})
	@:overload(function(vec3: Vec3): Void {})
	@:native("uvec3")
	public function new(uint: UInt);

	@:op(A == B) public static inline function equalsUVec3(me: UVec3, other: UVec3): Bool return untyped __gdshader__("({0} == {1})", me, other);
	@:op(A != B) public static inline function notEqualsUVec3(me: UVec3, other: UVec3): Bool return untyped __gdshader__("({0} != {1})", me, other);
	@:op(-A) public static inline function negate(me: UVec3): UVec3 return untyped __gdshader__("(-{0})", me);
	@:op(A + B) public static inline function addUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} + {1})", me, other);
	@:op(A + B) public static inline function addUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} + {1})", me, other);
	@:op(A - B) public static inline function subtractUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} - {1})", me, other);
	@:op(A - B) public static inline function subtractUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} - {1})", me, other);
	@:op(A * B) public static inline function multiplyUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} * {1})", me, other);
	@:op(A * B) public static inline function multiplyUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} * {1})", me, other);
	@:op(A / B) public static inline function divideUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} / {1})", me, other);
	@:op(A / B) public static inline function divideUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} / {1})", me, other);
	@:op(A % B) public static inline function modulusUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} % {1})", me, other);
	@:op(A % B) public static inline function modulusUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} % {1})", me, other);
	@:op(A << B) public static inline function shiftLeftUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} << {1})", me, other);
	@:op(A << B) public static inline function shiftLeftUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} << {1})", me, other);
	@:op(A >> B) public static inline function shiftRightUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} >> {1})", me, other);
	@:op(A >> B) public static inline function shiftRightUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} >> {1})", me, other);
	@:op(A += B) public static inline function addAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} += {1})", me, other);
	@:op(A += B) public static inline function addAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} += {1})", me, other);
	@:op(A -= B) public static inline function subtractAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} -= {1})", me, other);
	@:op(A -= B) public static inline function subtractAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} -= {1})", me, other);
	@:op(A *= B) public static inline function multiplyAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} *= {1})", me, other);
	@:op(A *= B) public static inline function multiplyAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} *= {1})", me, other);
	@:op(A /= B) public static inline function divideAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} /= {1})", me, other);
	@:op(A /= B) public static inline function divideAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} /= {1})", me, other);
	@:op(A %= B) public static inline function modulusAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} %= {1})", me, other);
	@:op(A %= B) public static inline function modulusAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} %= {1})", me, other);
	@:op(A <<= B) public static inline function shiftLeftAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} <<= {1})", me, other);
	@:op(A <<= B) public static inline function shiftLeftAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} <<= {1})", me, other);
	@:op(A >>= B) public static inline function shiftRightAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} >>= {1})", me, other);
	@:op(A >>= B) public static inline function shiftRightAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} >>= {1})", me, other);
	@:op(A &= B) public static inline function bitAndAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} &= {1})", me, other);
	@:op(A &= B) public static inline function bitAndAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} &= {1})", me, other);
	@:op(A |= B) public static inline function bitOrAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} |= {1})", me, other);
	@:op(A |= B) public static inline function bitOrAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} |= {1})", me, other);
	@:op(A ^= B) public static inline function bitXOrAssignUInt(me: UVec3, other: UInt): UVec3 return untyped __gdshader__("({0} ^= {1})", me, other);
	@:op(A ^= B) public static inline function bitXOrAssignUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} ^= {1})", me, other);
	@:op(A & B) public static inline function bitAndUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} & {1})", me, other);
	@:op(A | B) public static inline function bitOrUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} | {1})", me, other);
	@:op(A ^ B) public static inline function bitXOrUVec3(me: UVec3, other: UVec3): UVec3 return untyped __gdshader__("({0} ^ {1})", me, other);
	@:op(~A) public static inline function bitInvert(me: UVec3): UVec3 return untyped __gdshader__("(~{0})", me);
	@:op(++A) public static inline function increment(me: UVec3): UVec3 return untyped __gdshader__("(++{0})", me);
	@:op(--A) public static inline function decrement(me: UVec3): UVec3 return untyped __gdshader__("(--{0})", me);
	@:op(A++) public static inline function postIncrement(me: UVec3): UVec3 return untyped __gdshader__("({0}++)", me);
	@:op(A--) public static inline function postDecrement(me: UVec3): UVec3 return untyped __gdshader__("({0}--)", me);
	@:op(A + B) public static inline function addUIntFlipped(other: UInt, me: UVec3): UVec3 return untyped __gdshader__("({0} + {1})", other, me);
	@:op(A - B) public static inline function subtractUIntFlipped(other: UInt, me: UVec3): UVec3 return untyped __gdshader__("({0} - {1})", other, me);
	@:op(A * B) public static inline function multiplyUIntFlipped(other: UInt, me: UVec3): UVec3 return untyped __gdshader__("({0} * {1})", other, me);
	@:op(A / B) public static inline function divideUIntFlipped(other: UInt, me: UVec3): UVec3 return untyped __gdshader__("({0} / {1})", other, me);
}
